// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: staffer-protos/position.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title        string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description  string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DepartmentId string `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
}

func (x *CreatePosition) Reset() {
	*x = CreatePosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_position_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePosition) ProtoMessage() {}

func (x *CreatePosition) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_position_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePosition.ProtoReflect.Descriptor instead.
func (*CreatePosition) Descriptor() ([]byte, []int) {
	return file_staffer_protos_position_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePosition) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePosition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePosition) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type UpdatePosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title        string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description  string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DepartmentId string `protobuf:"bytes,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
}

func (x *UpdatePosition) Reset() {
	*x = UpdatePosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_position_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePosition) ProtoMessage() {}

func (x *UpdatePosition) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_position_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePosition.ProtoReflect.Descriptor instead.
func (*UpdatePosition) Descriptor() ([]byte, []int) {
	return file_staffer_protos_position_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePosition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePosition) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePosition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePosition) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type GetAllPositionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PositionId string `protobuf:"bytes,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VacansyId  string `protobuf:"bytes,3,opt,name=vacansy_id,json=vacansyId,proto3" json:"vacansy_id,omitempty"`
}

func (x *GetAllPositionsRequest) Reset() {
	*x = GetAllPositionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_position_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPositionsRequest) ProtoMessage() {}

func (x *GetAllPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_position_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPositionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllPositionsRequest) Descriptor() ([]byte, []int) {
	return file_staffer_protos_position_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllPositionsRequest) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *GetAllPositionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAllPositionsRequest) GetVacansyId() string {
	if x != nil {
		return x.VacansyId
	}
	return ""
}

type GetAllPositionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title        string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description  string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DepartmentId string `protobuf:"bytes,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Success      bool   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *GetAllPositionResponse) Reset() {
	*x = GetAllPositionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_position_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPositionResponse) ProtoMessage() {}

func (x *GetAllPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_position_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPositionResponse.ProtoReflect.Descriptor instead.
func (*GetAllPositionResponse) Descriptor() ([]byte, []int) {
	return file_staffer_protos_position_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllPositionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAllPositionResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetAllPositionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetAllPositionResponse) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *GetAllPositionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_staffer_protos_position_proto protoreflect.FileDescriptor

var file_staffer_protos_position_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x74, 0x61, 0x66, 0x66, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x1a, 0x19, 0x73, 0x74, 0x61, 0x66, 0x66, 0x65, 0x72, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6d, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x64,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0x7d, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x71, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x73, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x73, 0x79,
	0x49, 0x64, 0x22, 0x9f, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x32, 0xd9, 0x01, 0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x15, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0b, 0x2e, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x15, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0b, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e,
	0x56, 0x6f, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0b,
	0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x42, 0x79, 0x69, 0x64, 0x1a, 0x0b, 0x2e, 0x73, 0x74,
	0x61, 0x66, 0x66, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x46, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x12, 0x1d, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_staffer_protos_position_proto_rawDescOnce sync.Once
	file_staffer_protos_position_proto_rawDescData = file_staffer_protos_position_proto_rawDesc
)

func file_staffer_protos_position_proto_rawDescGZIP() []byte {
	file_staffer_protos_position_proto_rawDescOnce.Do(func() {
		file_staffer_protos_position_proto_rawDescData = protoimpl.X.CompressGZIP(file_staffer_protos_position_proto_rawDescData)
	})
	return file_staffer_protos_position_proto_rawDescData
}

var file_staffer_protos_position_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_staffer_protos_position_proto_goTypes = []any{
	(*CreatePosition)(nil),         // 0: staff.CreatePosition
	(*UpdatePosition)(nil),         // 1: staff.UpdatePosition
	(*GetAllPositionsRequest)(nil), // 2: staff.GetAllPositionsRequest
	(*GetAllPositionResponse)(nil), // 3: staff.GetAllPositionResponse
	(*Byid)(nil),                   // 4: staff.Byid
	(*Void)(nil),                   // 5: staff.Void
}
var file_staffer_protos_position_proto_depIdxs = []int32{
	0, // 0: staff.PositionService.Create:input_type -> staff.CreatePosition
	1, // 1: staff.PositionService.Update:input_type -> staff.UpdatePosition
	4, // 2: staff.PositionService.Delete:input_type -> staff.Byid
	2, // 3: staff.PositionService.GetAll:input_type -> staff.GetAllPositionsRequest
	5, // 4: staff.PositionService.Create:output_type -> staff.Void
	5, // 5: staff.PositionService.Update:output_type -> staff.Void
	5, // 6: staff.PositionService.Delete:output_type -> staff.Void
	3, // 7: staff.PositionService.GetAll:output_type -> staff.GetAllPositionResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_staffer_protos_position_proto_init() }
func file_staffer_protos_position_proto_init() {
	if File_staffer_protos_position_proto != nil {
		return
	}
	file_staffer_protos_void_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_staffer_protos_position_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_position_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UpdatePosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_position_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllPositionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_position_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllPositionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_staffer_protos_position_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_staffer_protos_position_proto_goTypes,
		DependencyIndexes: file_staffer_protos_position_proto_depIdxs,
		MessageInfos:      file_staffer_protos_position_proto_msgTypes,
	}.Build()
	File_staffer_protos_position_proto = out.File
	file_staffer_protos_position_proto_rawDesc = nil
	file_staffer_protos_position_proto_goTypes = nil
	file_staffer_protos_position_proto_depIdxs = nil
}
