// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: staffer-protos/resume.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResumeCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Education string `protobuf:"bytes,2,opt,name=education,proto3" json:"education,omitempty"`
	Summary   string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (x *ResumeCreate) Reset() {
	*x = ResumeCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_resume_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeCreate) ProtoMessage() {}

func (x *ResumeCreate) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_resume_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeCreate.ProtoReflect.Descriptor instead.
func (*ResumeCreate) Descriptor() ([]byte, []int) {
	return file_staffer_protos_resume_proto_rawDescGZIP(), []int{0}
}

func (x *ResumeCreate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResumeCreate) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *ResumeCreate) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ResumeGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Education string `protobuf:"bytes,3,opt,name=education,proto3" json:"education,omitempty"`
	Summary   string `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (x *ResumeGetRes) Reset() {
	*x = ResumeGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_resume_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeGetRes) ProtoMessage() {}

func (x *ResumeGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_resume_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeGetRes.ProtoReflect.Descriptor instead.
func (*ResumeGetRes) Descriptor() ([]byte, []int) {
	return file_staffer_protos_resume_proto_rawDescGZIP(), []int{1}
}

func (x *ResumeGetRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResumeGetRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResumeGetRes) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *ResumeGetRes) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ResumeUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Education string `protobuf:"bytes,2,opt,name=education,proto3" json:"education,omitempty"`
	Summary   string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (x *ResumeUpdate) Reset() {
	*x = ResumeUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_resume_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeUpdate) ProtoMessage() {}

func (x *ResumeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_resume_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeUpdate.ProtoReflect.Descriptor instead.
func (*ResumeUpdate) Descriptor() ([]byte, []int) {
	return file_staffer_protos_resume_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResumeUpdate) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *ResumeUpdate) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ResumeGetAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string      `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Education string      `protobuf:"bytes,3,opt,name=education,proto3" json:"education,omitempty"`
	Filter    *Pagination `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *ResumeGetAll) Reset() {
	*x = ResumeGetAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_resume_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeGetAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeGetAll) ProtoMessage() {}

func (x *ResumeGetAll) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_resume_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeGetAll.ProtoReflect.Descriptor instead.
func (*ResumeGetAll) Descriptor() ([]byte, []int) {
	return file_staffer_protos_resume_proto_rawDescGZIP(), []int{3}
}

func (x *ResumeGetAll) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResumeGetAll) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *ResumeGetAll) GetFilter() *Pagination {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ResumeGetAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resumes *ResumeGetRes `protobuf:"bytes,1,opt,name=Resumes,proto3" json:"Resumes,omitempty"`
	Success bool          `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ResumeGetAllRes) Reset() {
	*x = ResumeGetAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_resume_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeGetAllRes) ProtoMessage() {}

func (x *ResumeGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_resume_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeGetAllRes.ProtoReflect.Descriptor instead.
func (*ResumeGetAllRes) Descriptor() ([]byte, []int) {
	return file_staffer_protos_resume_proto_rawDescGZIP(), []int{4}
}

func (x *ResumeGetAllRes) GetResumes() *ResumeGetRes {
	if x != nil {
		return x.Resumes
	}
	return nil
}

func (x *ResumeGetAllRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_staffer_protos_resume_proto protoreflect.FileDescriptor

var file_staffer_protos_resume_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x74, 0x61, 0x66, 0x66, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x74, 0x61, 0x66, 0x66, 0x1a, 0x19, 0x73, 0x74, 0x61, 0x66, 0x66, 0x65, 0x72, 0x2d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x5f, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x64, 0x75, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x64, 0x75,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x22, 0x6f, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x64, 0x75,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x64,
	0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x22, 0x56, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x70, 0x0a, 0x0c, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x29, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x5a, 0x0a, 0x0f, 0x52,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x2d,
	0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xeb, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x1a, 0x0b, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0b, 0x2e, 0x73,
	0x74, 0x61, 0x66, 0x66, 0x2e, 0x42, 0x79, 0x69, 0x64, 0x1a, 0x13, 0x2e, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x2a,
	0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x0b, 0x2e,
	0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x0b, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x42, 0x79, 0x69,
	0x64, 0x1a, 0x0b, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x35,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x13, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x1a, 0x16, 0x2e,
	0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_staffer_protos_resume_proto_rawDescOnce sync.Once
	file_staffer_protos_resume_proto_rawDescData = file_staffer_protos_resume_proto_rawDesc
)

func file_staffer_protos_resume_proto_rawDescGZIP() []byte {
	file_staffer_protos_resume_proto_rawDescOnce.Do(func() {
		file_staffer_protos_resume_proto_rawDescData = protoimpl.X.CompressGZIP(file_staffer_protos_resume_proto_rawDescData)
	})
	return file_staffer_protos_resume_proto_rawDescData
}

var file_staffer_protos_resume_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_staffer_protos_resume_proto_goTypes = []any{
	(*ResumeCreate)(nil),    // 0: staff.ResumeCreate
	(*ResumeGetRes)(nil),    // 1: staff.ResumeGetRes
	(*ResumeUpdate)(nil),    // 2: staff.ResumeUpdate
	(*ResumeGetAll)(nil),    // 3: staff.ResumeGetAll
	(*ResumeGetAllRes)(nil), // 4: staff.ResumeGetAllRes
	(*Pagination)(nil),      // 5: staff.Pagination
	(*Byid)(nil),            // 6: staff.Byid
	(*Void)(nil),            // 7: staff.Void
}
var file_staffer_protos_resume_proto_depIdxs = []int32{
	5, // 0: staff.ResumeGetAll.filter:type_name -> staff.Pagination
	1, // 1: staff.ResumeGetAllRes.Resumes:type_name -> staff.ResumeGetRes
	0, // 2: staff.ResumeService.Create:input_type -> staff.ResumeCreate
	6, // 3: staff.ResumeService.Get:input_type -> staff.Byid
	2, // 4: staff.ResumeService.Update:input_type -> staff.ResumeUpdate
	6, // 5: staff.ResumeService.Delete:input_type -> staff.Byid
	3, // 6: staff.ResumeService.GetAll:input_type -> staff.ResumeGetAll
	7, // 7: staff.ResumeService.Create:output_type -> staff.Void
	1, // 8: staff.ResumeService.Get:output_type -> staff.ResumeGetRes
	7, // 9: staff.ResumeService.Update:output_type -> staff.Void
	7, // 10: staff.ResumeService.Delete:output_type -> staff.Void
	4, // 11: staff.ResumeService.GetAll:output_type -> staff.ResumeGetAllRes
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_staffer_protos_resume_proto_init() }
func file_staffer_protos_resume_proto_init() {
	if File_staffer_protos_resume_proto != nil {
		return
	}
	file_staffer_protos_void_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_staffer_protos_resume_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ResumeCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_resume_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ResumeGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_resume_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ResumeUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_resume_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ResumeGetAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_resume_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ResumeGetAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_staffer_protos_resume_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_staffer_protos_resume_proto_goTypes,
		DependencyIndexes: file_staffer_protos_resume_proto_depIdxs,
		MessageInfos:      file_staffer_protos_resume_proto_msgTypes,
	}.Build()
	File_staffer_protos_resume_proto = out.File
	file_staffer_protos_resume_proto_rawDesc = nil
	file_staffer_protos_resume_proto_goTypes = nil
	file_staffer_protos_resume_proto_depIdxs = nil
}
